name: Discord Notification

on:
  push:
    branches:
      - main
      - production
  pull_request:
    types: [closed]
    branches:
      - main
      - production

jobs:
  notify:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification on Push
        if: github.event_name == 'push'
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: "**Novo push na branch `${{ github.ref_name }}`**"
          embed-title: "${{ github.event.head_commit.message }}"
          embed-url: "${{ github.event.head_commit.url }}"
          embed-author-name: "${{ github.actor }}"
          embed-author-icon-url: "${{ github.event.sender.avatar_url }}"
          embed-color: 260292

      - name: Send Discord Notification on PR Merge
        if: github.event_name == 'pull_request'
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: "**Pull Request mergeado na branch `${{ github.base_ref }}`**"
          embed-title: "#${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}"
          embed-url: "${{ github.event.pull_request.html_url }}"
          embed-description: "${{ github.event.pull_request.body }}"
          embed-author-name: "${{ github.actor }}"
          embed-author-icon-url: "${{ github.event.sender.avatar_url }}"
          embed-color: 8311585